# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16nFYAopBLloaFrt1Qug4zHwbMKPMvykC

#**Creating a Unified Data Model**
This is to standardise both sources and its data frame will be used for the Dash map.
"""

from sqlalchemy import create_engine, text
import plotly.express as px
import pandas as pd

unified_sql_query = """
WITH latest_readings AS (
  SELECT
    r.device_id,
    r.species,
    r.value,
    r.time,
    ROW_NUMBER() OVER (
      PARTITION BY r.device_id, r.species
      ORDER BY r.time DESC
    ) AS rn
  FROM readings r
),
-- keeping only the latest reading because Render can't support historical data (too big)
latest_only AS(
    SELECT
      device_id,
      species,
      value,
      time
    FROM latest_readings
    -- because the readings are ranked from latest (desc order)
    -- 1 is calling the top reading for each device/species
    WHERE rn = 1
)
SELECT
  d.device_id,
  d.source,
  d.device_name,
  d.school_id,
  s.school_name,
  s.school_type,
  s.postcode,
  s.borough,
  s.centroid_lat AS latitude,
  s.centroid_lon AS longitude,
-- MAX ignores null values as CASE WHEN filters by species (value or null) per device
  MAX(CASE WHEN lo.species = 'PM25' THEN lo.value END) AS "PM2.5",
  MAX(CASE WHEN lo.species ='PM10' THEN lo.value END) AS "PM10",
  MAX(CASE WHEN lo.species = 'NO2' THEN lo.value END) AS "NO2",

  MAX(CASE WHEN lo.species = 'PM25' THEN lo.time END) AS "PM2.5_time",
  MAX(CASE WHEN lo.species ='PM10' THEN lo.time END) AS "PM10_time",
  MAX(CASE WHEN lo.species = 'NO2' THEN lo.time END) AS "NO2_time"

FROM devices d
JOIN schools s
  ON d.school_id = s.school_id
LEFT JOIN latest_only lo
  ON d.device_id = lo.device_id
-- use GROUP BY to get one row per device
GROUP BY
  d.device_id,
  d.source,
  d.device_name,
  d.school_id,
  s.school_name,
  s.school_type,
  s.postcode,
  s.borough,
  s.centroid_lat,
  s.centroid_lon

ORDER BY
  d.source,
  s.school_name,
  d.device_id;
"""

df_unified = pd.read_sql(unified_sql_query, engine)
print(df_unified)

"""#**Creating the Dashboard Analytics**
The dashboard will display Key Performace Indicators (KPI) such as number of active sensors, number of red alerts, and average pollutant levels.

In addition, the dashboard will include filters for borough, source, and school type filtering. There will also be a ranking chart to display the current five schools with high and low pollutants.

#**Creating the KPI calculation function**
"""

def build_KPIs(df):
  df = df.copy()

  # This section of code is for the number of active sensors
  # An active sensor is counted as long as it has 1 pollutant reading available
  active_pollutants = (
      df["PM2.5"].notna() |
      df["PM10"].notna() |
      df["NO2"].notna()
  )
  active_sensors = df.loc[active_pollutants, "device_id"].nunique()

  # This is for the number of red alerts per pollutant
  red_pm25 = df["PM25"].apply(lambda x: colour_code(x, "PM25")).eq("red").sum()
  red_pm10 = df["PM10"].apply(lambda x: colour_code(x, "PM10")).eq("red").sum()
  red_no2 = df["NO2"].apply(lambda x: colour_code(x, "NO2")).eq("red").sum()

  # This is for average pollutant levels per borough
  avg_pm25 = df["PM25"].mean()
  avg_pm10 = df["PM10"].mean()
  avg_no2 = df["NO2"].mean()

  borough_summary = (
      df.groupby("borough", dropna = False)[["PM25", "PM10", "NO2"]]
      .mean().reset_index().sort_values("borough")
  )
  return{
      "active_sensors": active_sensors,
      "red_pm25": int(red_pm25),
      "red_pm10": int(red_pm10),
      "red_no2": int(red_no2),
      "avg_pm25": avg_pm25,
      "avg_pm10": avg_pm10,
      "avg_no2": avg_no2,
      "borough_summary": borough_summary
  }

"""#**Creating the Ranking Chart function**"""

def build_ranking_chart(df, pollutant, n = 5):
  if pollutant not in ["PM2.5", "PM10", "NO2"]:
    raise ValueError("Polluntant must be one of PM2.5, PM10, NO2")

  df_ranking =df.copy()
  # Removing rows that currently don't have a reading
  # To ensure the ranking is done effectively
  df_ranking = df_ranking.dropna(subset = [pollutant])
  if df_ranking.empty:
    return px.bar(title = "No data currently available.")

  # Aggregate to school level
  df_ranking = (df_ranking.groupby(
      ["school_id", "school_name", "borough"],
      dropna = False)
  [pollutant].mean().reset_index()
  )

  top_rank = df_ranking.nlargest(n, pollutant).copy()
  top_rank["group"] = "Highest"

  bottom_rank = df_ranking.nsmallest(n, pollutant).copy()
  bottom_rank["group"] = "Lowest"

  df_ranking = pd.concat([top_rank, bottom_rank], ignore_indes = True)

  fig = px.bar(
      df_ranking,
      x = pollutant,
      y = "school_name",
      color = "group",
      hover_data = ["borough"],
      orientation = "h",
      title = f"Current highest and lowest {n} schools by {pollutant}"
  )

  fig.update_layout(yaxis = {"categoryorder": "total ascending"})
  return fig

"""#**Creating the average pollutant level per Borough bar chart function**"""

def build_borough_bar_chart(df, pollutant):
  if pollutant not in ["PM2.5", "PM10", "NO2"]:
    raise ValueError("Polluntant must be one of PM2.5, PM10, NO2")

  df_plot = (
      df.groupby("borough", dropna = False)[pollutant]
      .mean().reset_index().dropna(subset = [pollutant])
      .sort_values(pollutant, ascending = False)
  )
  if df_plot.empty:
    return px.bar(title = "No data currently available.")
  fig = px.bar(
      df_plot,
      x = "borough",
      y = pollutant,
      title = f"Current average {pollutant} levels per borough."
  )

"""#**Formatting the above functions when they are called during Dash**

"""

def fmt_num(x, digits = 1):
  if pd.isna(x):
    return "No data!"
  return f"{x:.{digits}f}"

"""#**Creating the filters and assigning colours to the pollutants boundary**"""

# Creating the filter function as this is needed in most of the dashboard.
def dashboard_filters(df, borough = None, source = None, school_type = None):
  df_filtered = df.copy()
  # The condition is for no filter applied and when user picks borough/source/school_type
  if borough and borough != "All":
    df_filtered = df_filtered[df_filtered["borough"] == borough]

  if source and source != "All":
    df_filtered = df_filtered[df_filtered["source"] == source]

  if school_type and school_type != "All":
    df_filtered = df_filtered[df_filtered["school_type"] == school_type]

  return df_filtered

# Now I will create the boundaries of each pollutant, NO2 & PM2.5
# I got the pollutant boundaries from DEFRA
Pollutant_boundaries = {
    "PM2.5":{"max_green": 35, "max_yellow": 53, "max_red": 70},
    "NO2":{"max_green": 200, "max_yellow": 400, "max_red": 600},
    "PM10":{"max_green": 50, "max_yellow": 75, "max_red": 100}
}

# The next stage is to convert the numbers to colours by creating a function
# This will then be called in the map creation to show the different pollutant level

def colour_code(value,species):
  if pd.isna(value):
    return "Unknown"

  limits = Pollutant_boundaries.get(species)
  if not limits:
    return "Unknown"
  if value <= limits["max_green"]:
    return "green"
  elif value <= limits["max_yellow"]:
    return "yellow"
  else:
    return "red"

"""#**Building the map**"""

from dash import Dash, dcc, html, Input, Output

# Now I am ready to create the map
def create_map(df, pollutant):
  df = df.copy()
  #Ensuring the coordinates are in the correct form and dropping any NaN vals
  df["latitude"] = pd.to_numeric(df["latitude"], errors = "coerce")
  df["longitude"] = pd.to_numeric(df["longitude"], errors = "coerce")
  df = df.dropna(subset = ["latitude", "longitude"])

  df["colour_code"] = df[pollutant].apply(lambda x: colour_code(x, pollutant))

  # Creating the colours on the map
  colour_landmark = {"green":"green", "yellow":"gold", "red":"red", "Unknown":"lightgray"}

  fig = px.scatter_mapbox(
      df,
      lat = "latitude",
      lon = "longitude",
      color = "colour_code",
      color_discrete_map = colour_landmark,
      hover_name = "school_name",
      # This is to call all the data I want to show when the mouse hovers/click over a landmark.
      custom_data = [
          "school_name",
          "borough",
          "school_type",
          "device_id",
          "source",
          "PM25",
          "PM10",
          "NO2"
          "colour_code"
      ],
      zoom = 10,
      height = 675
  )

  fig.update_traces(
      marker = {"size":11},
      hovertemplate = (
          "<b>%{customdata[0]}</b><br>"
          "Borough: %{customdata[1]}<br>"
          "School Type: %{customdata[2]}<br>"
          "Device ID: %{customdata[3]}<br>"
          "Source: %{customdata[4]}<br>"
          "PM2.5: %{customdata[5]}<br>"
          "PM10: %{customdata[6]}<br>"
          "NO2: %{customdata[7]}<br>"
          "Status: %{customdata[8]}<extra></extra>"
      )
  )

  fig.update_layout(
      mapbox_style = "open-street-map",
      # This removes white spaces around the map
      margin = dict(l = 0, r = 0, t = 0, b = 0),
      legend_title = "Air Quality for {pollutant} alert band"
  )
  return fig

"""#**Creating the Dash app**"""

# This creates the Dash app where all the layouts and callbacks are registered
app = Dash(__name__)
# This helps it to run in Render
server = app.server

app.layout = html.Div(
    style = {"maxWidth": "1400px", "margin": "0 auto", "padding": "20px"},
    # All the components created in children will be seen on the platform
    children = [
        html.H2("Inner London Air Quality Dashboard"),
        html.Div(
            style = {
                "display": "grid",
                "gridTemplateColumns": "repeat(4, 1fr)",
                "gap": "12px",
                "marginBottom": "20px"
            },
    children = [
        dcc.Dropdown(
            id = "borough_filter",
            options = [
                {"label": "All", "value": "All"}] +
                [{"label": b, "value": b} for b in sorted(df_unified["borough"].dropna().unique())],
            # This is the auto pollutant that will be shown when Dash runs.
            value = "All",
            clearable = False,
            placeholder = "Select a borough",
            ),
        dcc.Dropdown(
            id = "source_filter",
            options = [
                {"label": "All", "value": "All"}] +
                [{"label": s.replace("_"," ").title(), "value": s} for s in sorted(df_unified["source"].dropna().unique())],
            value = "All",
            clearable = False,
            placeholder = "Select a soure (Breathe London/ Air Gradient)",
        ),
        dcc.Dropdown(
            id = "school_type_filter",
            options = [
                {"label": "All", "value": "All"}] +
                [{"label": t, "value": t} for t in sorted(df_unified["school_type"].dropna().unique())],
            # This is the auto pollutant that will be shown when Dash runs.
            value = "All",
            clearable = False,
            placeholder = "Select a school type",
            ),
        dcc.Dropdown(
            id = "pollutant_filter",
            options = [
                {"label": "PM2.5", "value": "PM25"},
                {"label": "PM10", "value": "PM10"},
                {"label": "NO2", "value": "NO2"}],
            value = "PM25",
            clearable = False,
            placeholder = "Select a pollutant",
        ),
    ]
),

html.H3("School Map"),
dcc.Graph(id = "air_quality_map"),
        # This is where the sensor details will appear after clicking a landmark.
        html.H4("Selected Sensor Details"),
        html.Div(
            id = "selected_sensor_info",
            style ={
                "border": "1px solid lightgrey",
                "padding": "12px",
                "borderRadius": "6px",
                "marginTop": "12px",
                "marginBottom": "30px"
            }
        ),
        # KPI cards
        html.H3("Key Performance Indicators"),
        html.Div(
            style ={
                "display": "grid",
                "gridTemplateColumns": "repeat(7,1fr)",
                "gap": "12px",
                "marginBottom": "30px"
      },
      children = [
          html.Div(id = "active_sensors_card", style = {"border": "1px solid lightgrey", "padding":"12px", "borderRadius": "8px"}),
          html.Div(id = "red_pm25_card", style = {"border": "1px solid lightgrey", "padding":"12px", "borderRadius": "8px"}),
          html.Div(id = "red_pm10_card", style = {"border": "1px solid lightgrey", "padding":"12px", "borderRadius": "8px"}),
          html.Div(id = "red_no2_card", style = {"border": "1px solid lightgrey", "padding":"12px", "borderRadius": "8px"}),
          html.Div(id = "average_pm25_card", style = {"border": "1px solid lightgrey", "padding":"12px", "borderRadius": "8px"}),
          html.Div(id = "average_pm10_card", style = {"border": "1px solid lightgrey", "padding":"12px", "borderRadius": "8px"}),
          html.Div(id = "average_no2_card", style = {"border": "1px solid lightgrey", "padding":"12px", "borderRadius": "8px"}),
      ]
    ),
    # Ranking chart
    html.H3("Current Ranking of Schools (Highest & Lowest)"),
    dcc.Graph(id = "ranking_chart"),

    # Borough avg chart
    html.H3("Average Pollutant Level per Borough"),
    dcc.Graph(id = "borough_avg_chart"),
  ]
)

"""#**Creating the map callback**

This is when user interacts on Render while using the map and the code below calls the applicable function created above.
"""

@app.callback(
    Output("air_quality_map", "figure"),
    Input("borough_filter", "children"),
    Input("source_filter", "children"),
    Input("school_type_filter", "children"),
    Input("pollutant_filter", "children")
)

def update_map(borough, source, school_type, pollutant):
  df_filtered = dashboard_filters(
      df_unified,
      borough = borough,
      source = source,
      school_type = school_type
  )
  return create_map(df_filtered, pollutant)

"""#**Creating the Clickable Marker callback**

This is when user interacts on Render while using the map and the code below calls the applicable function created above.
"""

# Creating the clickable marker
@app.callback(
    Output("selected_sensor_info", "children"),
    Input("air_quality_map", "clickData")
)
def display_sensor_deets(clickData):
  if clickData is None:
    return "Click on a marker to see a school sensor details."

  school_name, borough, school_type, device_id, source, pm25, pm10, no2, colour_code = clickData["points"][0]["customdata"]

  return html.Ul([
        html.Li([html.B("School: "), str(school_name)]),
        html.Li([html.B("Borough: "), str(borough)]),
        html.Li([html.B("School Type: "), str(school_type)]),
        html.Li([html.B("Device ID: "), str(device_id)]),
        html.Li([html.B("Source: "), str(source)]),
        html.Li([html.B("PM2.5: "), fmt_num(pm25)]),
        html.Li([html.B("PM10: "), fmt_num(pm10)]),
        html.Li([html.B("NO2: "), fmt_num(no2)]),
        html.Li([html.B("Colour alert: "), str(colour_code)])

    ])

"""#**Creating the KPIs card callback**

This is when user interacts on Render while using the map and the code below calls the applicable function created above.
"""

@app.callback(
    Output("active_sensors_card", "children"),
    Output("red_pm25_card", "children"),
    Output("red_pm10_card", "children"),
    Output("red_no2_card", "children"),
    Output("average_pm25_card", "children"),
    Output("average_pm10_card", "children"),
    Output("average_no2_card", "children"),
    Input("borough_filter", "children"),
    Input("source_filter", "children"),
    Input("school_type_filter", "children"),
    Input("pollutant_filter", "children")
)
def update_KPI_cards(borough, source, school_type):
  df_filtered = dashboard_filters(
      df_unified,
      borough = borough,
      source = source,
      school_type = school_type
  )

  KPIs = build_KPIs(df_filtered)

  active_sensors_card = html.Div([
      html.H4("Active Sensors"),
      html.H2(KPIs["active_sensors"])
  ])
  red_pm25_card = html.Div([
      html.H4("Red PM2.5 Alerts"),
      html.H2(KPIs["red_pm25"])
  ])
  red_pm10_card = html.Div([
      html.H4("Red PM10 Alerts"),
      html.H2(KPIs["red_pm10"])
  ])
  red_no2_card = html.Div([
      html.H4("Red NO2 Alerts"),
      html.H2(KPIs["red_no2"])
  ])
  average_pm25_card = html.Div([
      html.H4("Average PM2.5 Levels"),
      html.H2(fmt_num(KPIs["avg_pm25"]))
  ])
  average_pm10_card = html.Div([
      html.H4("Average PM10 Levels"),
      html.H2(fmt_num(KPIs["avg_pm10"]))
  ])
  average_no2_card = html.Div([
      html.H4("Average NO2 Levels"),
      html.H2(fmt_num(KPIs["avg_pmno2"]))
  ])

  return(
      active_sensors_card,
      red_pm25_card,
      red_pm10_card,
      red_no2_card,
      average_pm25_card,
      average_pm10_card,
      average_no2_card
  )

"""#**Creating the Ranking chart callback**

This is when user interacts on Render while using the map and the code below calls the applicable function created above.
"""

@app.callback(
    Output("ranking_chart", "figure"),
    Input("brough_filter", "value"),
    Input("source_filter", "value"),
    Input("school_type_filter", "value"),
    Input("pollutant_filter", "value")
)
def update_ranking_chart(borough, source, school_type, pollutant):
  df_filtered = dashboard_filters(
      df_unified,
      borough = borough,
      source = source,
      school_type = school_type
  )
  return build_ranking_chart(df_filtered, pollutant, n = 5)

"""#**Creating the average pollutant per Borough chart callback**

This is when user interacts on Render while using the map and the code below calls the applicable function created above.
"""

@app.callback(
    Output("borough_avg_chart", "figure"),
    Input("borough_filter", "value"),
    Input("source_filter", "value"),
    Input("school_type_filter", "value"),
    Input("pollutant_filter", "value")
)
def update_borough_avg_chart(borough, source, school_type, pollutant):
  df_filtered = dashboard_filters(
      df_unified,
      borough = borough,
      source = source,
      school_type = school_type
  )
  return build_borough_bar_chart(df_filtered, pollutant)

if __name__ == "__main__":
    app.run(debug=True)