# -*- coding: utf-8 -*-
"""EDA for BL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TeJ7T6JN2D0FjKdcKzokJ-LWmuQZS6TK
"""

import requests
import plotly.express as px
import re
import pandas as pd

# API consumption using BreatheLondon's API
BL_API_KEY = os.getenv("BL_API_KEY")
#blAPI_key = ""
# Sensor data is to colour code the markers and show the readings
List_sensors_URL = "https://breathe-london-7x54d7qf.ew.gateway.dev/ListSensors"
# Creating a dict of http headers to send a request to the Breathe London server to get what I need from the API
# Following the website (Breathe London) they said I need 2 headers to call the metadata
BL_headers = {
    "X-API-KEY": BL_API_KEY,
    #"X-API-KEY": blAPI_key,
    "Content-Type": "application/json"
}
# Now I can request for json metadata
# I can check if the requests is working through the 2nd line
def get_metadata():
  r = requests.get(List_sensors_URL, headers = BL_headers, timeout = 60)
  r.raise_for_status()
# Since the json file isn't in the correct format for python, I have to convert it into the proper dict that python understands
  return pd.DataFrame(r.json())

df_sensors = get_metadata()

# Viewing the data structure for BL
print ("Data Structure:\n", df_sensors.head())

# Parsing datetime
df_sensors["StartDate"] = pd.to_datetime(df_sensors["StartDate"], errors ="coerce")
df_sensors["EndDate"] = pd.to_datetime(df_sensors["EndDate"], errors ="coerce")

# Seeing when was the most recent and oldest installation
print ("Most recent installation:", df_sensors["StartDate"].max())
print ("The oldest installation:", df_sensors["StartDate"].min())

print("Number of sensors deployed:", len(df_sensors))

# Finding out the number of features, their name, and data types
print("Number of features:",df_sensors.shape[1])
print("\n Feature names:",df_sensors.columns.tolist())
print("\n Their data types:",df_sensors.dtypes)

# Generating a summary statistics
print("Numerical Summary Statistics\n",df_sensors.describe())
print("Categorical Summary Statistics\n",df_sensors.describe(include = "object"))
print("Number of Unique Sensors\n ",df_sensors["SiteCode"].nunique())
print("Number of Unique Locations\n ",df_sensors["SiteName"].nunique())
print("Number of Missing values in raw data",df_sensors.isna().sum())