# -*- coding: utf-8 -*-
"""SchoolPostcodes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uItbI74pxJs-tevKjyUhY1FjjhotOy7l
"""

import pandas as pd

# getting the list of schools in london so I can match the postcode centroid to respective school
df = pd.read_csv("/content/drive/MyDrive/edubasealldata20260414.csv", encoding = "latin-1", low_memory = False)
print (df.head())

df = df[df["EstablishmentStatus (code)"] == 1]
print ("Removed closed schools.", df.shape)

df =df[df["PhaseOfEducation (name)"].isin(["Primary", "Secondary"])]
print ("Kept only Primary and Secondary schools.")

inner_london_boroughs = [
    "Camden", "Hackney", "Hammersmith and Fulham", "Haringey", "Islington",
    "Kensington and Chelsea", "Lambeth", "Lewisham", "Newham", "Southwark",
    "Tower Hamlets", "Wandsworth", "Westminster", "City of London"
]

df =df[df["LA (name)"].isin(inner_london_boroughs)]
# Ensure that only the inner london schools are kept.
print ("List of schools in inner London.", df["LA (name)"].unique())

# Keeping only the columns needed
df = df[[
    "URN",
    "EstablishmentName",
    "Postcode",
    "LA (name)",
    "PhaseOfEducation (name)"
]]
df.head(5)

# Renaming the column names to match the TimescaleDB, Breathe Air, and AirGradient variables.
df = df.rename(columns = {
    "URN": "school_id",
    "EstablishmentName": "school_name",
    "Postcode": "postcode",
    "LA (name)": "borough",
    "PhaseOfEducation (name)": "school_type"
})
list(df.columns)

# doing postcode normalisation so that its uniform with the other files
def normalisation(postcode):
    p = postcode.strip().upper().replace(" ", "")
    if len(p) > 3:
        p = p[:-3] + " " + p[-3:]
    return p

df["postcode"] = df["postcode"].apply(normalisation)

df.to_csv("clean_inner_london_schools.csv", index = False)

print("Dataset saved.")