# -*- coding: utf-8 -*-
"""SQL_Creation_APIs_Ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7IWSD9d-TL2aFILAf8_yQzidYC603Xq

# **Creating the SQL tables**
"""

!pip install sqlalchemy psycopg2-binary

import os
from sqlalchemy import create_engine, text

# Creating a connection point for my Breathe & Airgradient ingestion codes, dashboard queries, and schema setup
os.environ["DATABASE_URL"] = "postgresql://ywsjl2130:KqVwIi3iqlz15pVuvKGB6ynpBF4e6rEZ@dpg-d7edd6hkh4rs73aarmlg-a.oregon-postgres.render.com/timescaledb_473l"

def get_database_URL ():
  URL = os.environ.get("DATABASE_URL")
  #URL = os.getenv("DATABASE_URL")
  if not URL:
    raise RuntimeError("Database URL is not set up")
  return URL

# Creating a connection manager for python code to interact with PostgreSQL
engine = create_engine(
    get_database_URL(),
    # Prevents stale connections as some connections may be "sleeping"
    pool_pre_ping = True,
    # This is so that SQL uses its latest style
    future = True
)

with engine.connect() as connection:
  result = connection.execute(text("SELECT NOW()")) # lets Alchemy know that it's a SQL query and not python
  print(result.scalar())

#with engine.begin() as conn:
    #conn.execute(text("CREATE EXTENSION timescaledb;"))

with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT extname
        FROM pg_extension
        WHERE extname = 'timescaledb';
    """))
    print(result.fetchall())

with engine.connect() as conn:
  result = conn.execute(text("""
      SELECT proname
      FROM pg_proc
      WHERE proname = 'create_hypertable';
  """))
  print(result.fetchall())

sql_file = """
CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS schools (
    school_id TEXT PRIMARY KEY,
    school_name TEXT NOT NULL,
    school_type TEXT,
    postcode TEXT NOT NULL,
    borough TEXT,
    centroid_lat DOUBLE PRECISION,
    centroid_lon DOUBLE PRECISION,
    install_date DATE
);

CREATE TABLE IF NOT EXISTS devices (
    device_id TEXT PRIMARY KEY,
    source TEXT NOT NULL, -- breatheLondon or AirGradient
    school_id TEXT REFERENCES schools(school_id),
    device_name TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS readings (
    time TIMESTAMPTZ NOT NULL,
    device_id TEXT NOT NULL REFERENCES devices(device_id),
    species TEXT NOT NULL, --pollutant type
    value DOUBLE PRECISION,
    status TEXT NOT NULL
);

SELECT create_hypertable('readings', 'time', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS idx_readings_device_time ON readings (device_id, time DESC);

CREATE INDEX IF NOT EXISTS idx_readings_species_time ON readings (species, time DESC);
"""

with engine.begin() as connection:
  for stmt in sql_file.split(";"):
    stmt = stmt.strip()
    if stmt:
      connection.execute(text(stmt))
print("Schema created successfully!")

# Checking if the tables and hypertable was created
with engine.connect() as conn:
    print(conn.execute(text("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
        ORDER BY table_name;
    """)).fetchall())

with engine.connect() as conn:
    print(conn.execute(text("""
        SELECT hypertable_name
        FROM timescaledb_information.hypertables;
    """)).fetchall())

"""# **Inserting data into the school table**"""

import pandas as pd

df_pcIL = pd.read_csv("https://raw.githubusercontent.com/ywsjl/Air-Pulse-Air-Quality-Map-Dashboard/refs/heads/main/postcode_centroid_inner_london_schools.csv")
list(df_pcIL.columns)

# Checking to see if the data types for the variables are correct
# Before I insert data into the school table
print(df_pcIL.dtypes)

# Dropping any duplicates because I forgot to do that previously
df_pcIL = df_pcIL.drop_duplicates(subset = ["school_id"])
# Need to rename longitude and latitude as its diff under the SQL table
df_pcIL = df_pcIL.rename(columns = {
    "centroid_latitude": "centroid_lat",
    "centroid_longitude":"centroid_lon"
})
list(df_pcIL.columns)

insert_sql = """
    INSERT INTO schools (
      school_id,
      school_name,
      school_type,
      postcode,
      borough,
      centroid_lat,
      centroid_lon
    )
    -- assigning data into the tables
    VALUES(
      :school_id,
      :school_name,
      :school_type,
      :postcode,
      :borough,
      :centroid_lat,
      :centroid_lon
    )
    -- This helps update the existing schools instead of crashing
    ON CONFLICT (school_id) DO UPDATE SET
      school_name = EXCLUDED.school_name,
      school_type = EXCLUDED.school_type,
      postcode = EXCLUDED.postcode,
      borough = EXCLUDED.borough,
      centroid_lat = EXCLUDED.centroid_lat,
      centroid_lon = EXCLUDED.centroid_lon
"""

with engine.begin() as connection:
  connection.execute(text(insert_sql), df_pcIL.to_dict(orient = "records"))

print("Schools database is successfully populated (seeded).")

# Double check it actually got seeded

verify_df = pd.read_sql("SELECT * FROM schools LIMIT 5", engine)
print(verify_df)

"""# **Breathe London API Ingestion**"""

import requests
import plotly.express as px
import re

# API consumption using BreatheLondon's API
#API_key = os.getenv("BL_API_KEY")
blAPI_key = "AIzaSyCO8yvEqQ8_T7xqBH73Iyes62nu4AtesP4"
# The metadata for list sensors will be used to place markers on the map
# Sensor data is to colour code the markers and show the readings
List_sensors_URL = "https://breathe-london-7x54d7qf.ew.gateway.dev/ListSensors"
Sensor_data_URL = "https://breathe-london-7x54d7qf.ew.gateway.dev/SensorData"
# Creating a dict of http headers to send a request to the Breathe London server to get what I need from the API
# Following the website (Breathe London) they said I need 2 headers to call the metadata
BL_headers = {
    #"X-API-KEY": BL_API_KEY,
    "X-API-KEY": blAPI_key,
    "Content-Type": "application/json"
}

# Now I can request for json metadata
# I can check if the requests is working through the 2nd line
def get_metadata():
  r = requests.get(List_sensors_URL, headers = BL_headers, timeout = 60)
  r.raise_for_status()
# Since the json file isn't in the correct format for python, I have to convert it into the proper dict that python understands
  return pd.DataFrame(r.json())

# Small EDA to see if the above is running smoothly, the features in the metadata, and number of sensors they have
df_sensors = get_metadata()
# Filtering the dataframe so that location = school only appears
df_sensors = df_sensors[
    df_sensors["SiteLocationType"].astype(str).str.lower() == "school"
].copy()
# Checking if the above code worked and only give school devices
print(df_sensors["SiteLocationType"].unique())
print(len(df_sensors))
print(df_sensors.columns.tolist())

"""Multiple device_ids were being assigned to the same SiteName(school) but since each school is only supposed to have 1 sensor -> 1 school, I am creating a code that remmoves devices and only keeps the device with the latest readings to be matched to the school.

"""

# Using the sensor data url to call the necessary latest readings which is PM2.5 & NO2
def sensor_readings(species):
  parameters = {"Species": species}
  readings_data = requests.get(Sensor_data_URL, headers = BL_headers, timeout = 60, params= parameters)
  readings_data.raise_for_status()
# Since the json file isn't in the correct format for python, I have to convert it into the proper dict that python understands
  return pd.DataFrame(readings_data.json())

dfBL_PM25 = sensor_readings("PM25")
dfBL_NO2 = sensor_readings("NO2")

df_pm25_time = dfBL_PM25[["SiteCode", "DateTime"]].copy()
df_no2_time = dfBL_NO2[["SiteCode", "DateTime"]].copy()
  # This converts the str DateTime pulled from the API to an actual datetime format
  # In case some of the string cant be converted I used errors so that it will not crash the code
df_pm25_time["DateTime"] = pd.to_datetime(df_pm25_time["DateTime"], errors = "coerce", utc = True)
df_no2_time["DateTime"] = pd.to_datetime(df_no2_time["DateTime"], errors = "coerce", utc = True)

# Pulling the latest time seen per device
df_pm25_latest_time = (
    df_pm25_time
    .groupby("SiteCode", as_index = False)["DateTime"]
    .max()
    .rename(columns = {"DateTime": "pm25_time"})
)

df_no2_latest_time = (
    df_no2_time
    .groupby("SiteCode", as_index = False)["DateTime"]
    .max()
    .rename(columns = {"DateTime": "no2_time"})
)

df_sensors_final = df_sensors.copy()

df_sensors_final = df_sensors_final.merge(df_pm25_latest_time, on = "SiteCode", how = "left")
df_sensors_final = df_sensors_final.merge(df_no2_latest_time, on = "SiteCode", how = "left")

df_sensors_final["latest_time"] = df_sensors_final[["pm25_time", "no2_time"]].max(axis = 1)

df_sensors_final = df_sensors_final.sort_values(
    by = ["SiteName", "latest_time"],
    ascending = [True, False]
)

df_sensors_final = df_sensors_final.drop_duplicates(subset = ["SiteName"], keep = "first").copy()
print("One sensor per school:", len(df_sensors_final))
print(df_sensors_final[["SiteCode","SiteName", "latest_time"]].head(40))

"""There are 58 sensors per school which meant without doing this step, almost half of the intial 101 sensors were "duplicates" for some schools."""

# This is to double confirm that all duplicates have been removed.
dupes = df_sensors_final[df_sensors_final.duplicated(subset=["SiteName"], keep=False)]
print("Duplicate SiteName rows remaining:", len(dupes))

if not dupes.empty:
    print(dupes[["SiteCode", "SiteName", "latest_time"]].sort_values("SiteName").to_string(index=False))
else:
    print("Success: 1 sensor per SiteName.")

# Normalising the borough name
def normalise_borough(y):
  if pd.isna(y):
    return None
  return str(y).strip().lower()
# Creating a new column in each dataframe for the normalised borough and changing SiteName to school_name for BL sensors
df_sensors_final["school_name"] = df_sensors_final["SiteName"]
df_sensors_final["borough_norm"] = df_sensors_final["Borough"].apply(normalise_borough)
df_pcIL["borough_norm"] = df_pcIL["borough"].apply(normalise_borough)

"""# **Merging Breathe London sensors to postcode centroid inner London schools to create a new dataframe**"""

df_match_both_sch_bor = (
    df_pcIL.sort_values("school_id")
    .drop_duplicates(subset = ["school_name","borough_norm"]).copy()
)

df_match_both = df_sensors_final.merge(
    df_match_both_sch_bor[
        [
            "school_id",
            "school_name",
            "school_type",
            "postcode",
            "borough",
            "borough_norm",
            "centroid_lat",
            "centroid_lon"
        ]
    ],
    on = ["school_name","borough_norm"],
    how = "left",
    suffixes = ("_sensor", "_school")
)

df_unmatched = df_match_both[df_match_both["school_id"].isna()].copy()
print("Strict Matched Schools:", df_match_both["school_id"].notna().sum())
print("Strict Unmatched Schools:", len(df_unmatched))

# Checking if it was correctly matched
columns = [
    "SiteCode",
    "SiteName",
    "school_id",
    "school_name",
    "borough_norm"
]

df_check = df_match_both[df_match_both["school_id"].notna()][columns].copy()
print(df_check.sort_values("school_name").to_string(index = False))

"""The total number of matched sensors to the inner London postcode centroid schools is 58."""

# Changing all the coordinates from Breathe London to centroid coordinates
df_match_both["Latitude"] = df_match_both["centroid_lat"]
df_match_both["Longitude"] = df_match_both["centroid_lon"]

df_devices = df_match_both[
    df_match_both["school_id"].notna()]
[["SiteCode",
     "SiteName",
     "school_id"
    ]
].copy()

df_devices = df_devices.rename(
    columns = {
        "SiteCode": "device_id",
        "SiteName": "device_name"
    }
)

df_devices["source"] = "breathe_london"
df_devices = df_devices[["device_id","source","school_id","device_name"]]

print(df_devices.head())

"""# **Inserting data into the device table**"""

print(df_devices.dtypes)

def seed_devices(df_devices, engine):
  required_cols = ["device_id", "source", "school_id","device_name"]
  missing = [col for col in required_cols if col not in df_devices.columns]
  if missing:
    raise ValueError(f"Missing required columns:{missing}")

  df_devices = df_devices[required_cols].copy()
  # To keep it consistent with schools table
  df_devices["school_id"] = pd.to_numeric(
      df_devices["school_id"],
      errors = "coerce"
  ).astype("Int64").astype(str)

  db_school_id = pd.read_sql(
      "SELECT school_id FROM schools",
      engine
  )
  valid_school_ids = set(db_school_id["school_id"].astype(str).tolist())

  df_devices = df_devices[df_devices["school_id"].isin(valid_school_ids)].copy()
  print("Rows ready to be inserted:", len(df_devices))

  insert_devices_sql = """
    INSERT INTO devices(
      device_id,
      source,
      school_id,
      device_name
    )
    VALUES(
      :device_id,
      :source,
      :school_id,
      :device_name
    )
    ON CONFLICT (device_id) DO UPDATE SET
      source = EXCLUDED.source,
      school_id = EXCLUDED.school_id,
      device_name = EXCLUDED.device_name
  """
  records = df_devices.to_dict(orient = "records")
  with engine.begin() as connection:
    connection.execute(text(insert_devices_sql), records)
  print("Devices database is successfully populated (seeded).")

seed_devices(df_devices, engine)

# Double check it actually got seeded

verify_df = pd.read_sql("SELECT * FROM devices LIMIT 5", engine)
print(verify_df)

# Checking if there are still any duplicates that may not have been removed initially
pd.read_sql("""
SELECT device_id, COUNT(*) AS n
FROM devices
GROUP BY device_id
HAVING COUNT(*) > 1
ORDER BY n DESC;
""", engine)

"""# **Calling the necessary data needed for the Breathe London Readings dataframe.**"""

# Seeing the number of raw readings before pulling the matched deivce readings.
dfBL_rawPM25 = sensor_readings("PM25")
dfBL_rawNO2 = sensor_readings("NO2")
print("PM2.5 Readings:", len(dfBL_rawPM25))
print("NO2 Readings:", len(dfBL_rawNO2))

BLdevice_ids = set(
    df_devices.loc[df_devices["source"]== "breathe_london","device_id"].astype(str)
)
print("Matched BL device IDs:", len(BLdevice_ids))

# Using the list of device IDs called from above, to filter the readings pulled above  and match the sensors
dfBL_PM25 = dfBL_rawPM25[
    dfBL_rawPM25["SiteCode"].astype(str).isin(BLdevice_ids)
].copy()

dfBL_NO2 = dfBL_rawNO2[
    dfBL_rawNO2["SiteCode"].astype(str).isin(BLdevice_ids)
].copy()

print("Filtered PM2.5 Readings:", len(dfBL_PM25))
print("Filtered NO2 Readings:", len(dfBL_NO2))

def latest_snapshot(dfBL, species_name):
  # Keeping only the features required
  dfBL = dfBL[["SiteCode","ScaledValue","DateTime","Species"]].copy()

  # This converts the str DateTime pulled from the API to an actual datetime format
  # In case some of the string cant be converted I used errors so that it will not crash the code
  dfBL["DateTime"] = pd.to_datetime(dfBL["DateTime"], errors = "coerce", utc = True)
  dfBL["ScaledValue"] = pd.to_numeric(dfBL["ScaledValue"], errors = "coerce")

  # Keep the latest readings per sensor per site code (school)
  # Tail (1) gives me the last row from each group which is the latest reading
  dfBL = dfBL.sort_values("DateTime").groupby("SiteCode").tail(1)

  # To match the Readings table
  dfBL = dfBL.rename(columns = {
        "SiteCode": "device_id",
        "DateTime": "time",
        "ScaledValue": "value",
        "Species": "species"
  })
  dfBL["status"] = "latest"

  # Getting rid of invalid rows
  dfBL = dfBL.dropna(subset = ["time", "device_id", "value","species"]).copy()

  return dfBL

# Creating the pollutants snapshot dataframes and merging them
dfBL_ss_PM25 = latest_snapshot(dfBL_PM25, "PM25")
dfBL_ss_NO2 = latest_snapshot(dfBL_NO2, "NO2")

dfBL_ss = pd.concat(
    [dfBL_ss_PM25, dfBL_ss_NO2],
    ignore_index = True
)

# Checking if it worked
# It should roughly correspond with total number of readings,240. (from EDA output)
print(dfBL_ss.head())
print("Rows in Breathe London snapshot:", len(dfBL_ss))

"""The output for valid ss reading devices are 21. However, this may change someitmes depending on the time as certain devices may not call readings every hour.

#**Ensuring that there are no duplicates**

Because in the event it was not done, this step ensures no errors arise.
"""

# Checking if there are any duplicates that may not have been removed initially
pd.read_sql("""
SELECT device_id, COUNT(*) AS n
FROM readings
GROUP BY time, device_id, species
HAVING COUNT(*) > 1
ORDER BY n DESC;
""", engine)

"""# **Inserting these readings into the Readings table.**"""

# Editing the Readings table because I need to add constraints
# To use in ON CONFLICT which prevents adding duplicate readings
with engine.begin() as connection:
  connection.execute(text("""
  DO $$
  BEGIN
      IF NOT EXISTS(
        -- checking if this constraint has already been added
          SELECT 1
          FROM pg_constraint
          WHERE conname = 'unique_reading'
       ) THEN
            ALTER TABLE readings
            ADD CONSTRAINT unique_reading
            -- all 3 is required because even though id is unique
            -- since there are multiple pollutants, there will be more than 1 of the same id
            UNIQUE (time,device_id,species);
          END IF;
  END $$;
  """))

print("Unique constraints have been added to Readings table.")

def seed_readings(df_readings, engine):
  required_cols = ["time", "device_id", "species","value", "status"]
  missing = [col for col in required_cols if col not in df_readings.columns]
  if missing:
    raise ValueError(f"Missing required columns:{missing}")

  df_readings = df_readings[required_cols].copy()
  # For Nan values
  df_readings = df_readings.dropna(subset = ["time", "device_id", "species","value"]).copy()
  # In case of duplicates
  df_readings = df_readings.drop_duplicates(subset = ["time", "device_id", "species"])

  print("Rows ready to be inserted:", len(df_readings))
  print(df_readings.head())

  insert_readings_sql = """
    INSERT INTO readings(
      time,
      device_id,
      species,
      value,
      status
    )
    VALUES(
      :time,
      :device_id,
      :species,
      :value,
      :status
    )
    ON CONFLICT (time, device_id, species) DO UPDATE SET
      value = EXCLUDED.value,
      status = EXCLUDED.status
  """

  records = df_readings.to_dict(orient = "records")
  with engine.begin() as connection:
    connection.execute(text(insert_readings_sql), records)
  print("Readings database is successfully populated (seeded).")

seed_readings(dfBL_ss, engine)

# Double check it actually got seeded
verify_df = pd.read_sql("SELECT * FROM readings LIMIT 5", engine)
print(verify_df)

"""# **Creating Air Gradient manual registry**

AirGradient's API URLs require location ID which is unique to each device as it is a private data platform. However, as I do not have all the location ID for inner London I cannot pull the metadata.

Thus, I have decided create a small manual registry and will connect this to the device registration.

The school ID that will be used below is not from a device placed in a school. But for this coursework, I applied an approximate mapping for the device which resulted in Millbank Gardens Primary Academy, being selected as it's the closest coordinates to the device.
"""

dfAG_registry = pd.DataFrame([
  {
      "device_id": "151755",
      "device_name": "Westminster, Horseferry Road",
      "school_id": "151310"
  }
])

dfAG_registry["source"] = "airgradient"
print(dfAG_registry)

"""#**Seeding Air Gradient device to Devices table**"""

dfAG_devices = dfAG_registry[
    ["device_id", "source", "school_id", "device_name"]
].copy()

# Assigning the data type
dfAG_devices["device_id"] = dfAG_devices["device_id"].astype(str)
dfAG_devices["source"] = dfAG_devices["source"].astype(str).str.strip().str.lower()
dfAG_devices["school_id"] = pd.to_numeric(dfAG_devices["school_id"], errors = "coerce").astype("Int64")
dfAG_devices["device_name"] = dfAG_devices["device_name"].astype(str).str.strip()

print(dfAG_devices.dtypes)
print(dfAG_devices)

seed_devices(dfAG_devices, engine)

# Double checking if it was seeded
print(pd.read_sql("SELECT * FROM devices WHERE source = 'airgradient'", engine))

"""# **Air Gradient API Ingestion**

"""

# API consumption using AirGradient's API
#API_key = os.getenv("AG_API_KEY")
AG_API_KEY = "92e55b50-1f00-483b-8fbf-3c96bb6f3c91"

def AGcurrent_measures(location_id):
  # Using this API to get the current reading of the device
  locations_URL = f"https://api.airgradient.com/public/api/v1/locations/{location_id}/measures/current?token={AG_API_KEY}"
  AG_headers = {
    #"X-API-KEY": BL_API_KEY,
    "X-API-KEY": blAPI_key,
    "Content-Type": "application/json"
  }
  # Now I can request for json metadata
  # I can check if the requests is working through the 2nd line
  r = requests.get(locations_URL, headers = AG_headers, timeout = 60)
  r.raise_for_status()
  return r.json()

# Checking if it works
AG_pulled_readings = AGcurrent_measures("151755")
print(AG_pulled_readings)

"""#**Renaming the columns to match Readings table**"""

def AG_pulled_readings_to_ss(pulled_AGreadings):
  timestamp = pulled_AGreadings.get("timestamp")
  timestamp = pd.to_datetime(timestamp, errors = "coerce", utc= True)

  device_id = str(pulled_AGreadings.get("locationId"))

  rows = [
      {
      "time": timestamp,
      "device_id": device_id,
      "species": "PM25",
      "value": pd.to_numeric(pulled_AGreadings["pm02"], errors = "coerce"),
      "status": "latest"
  },
    {
      "time": timestamp,
      "device_id": device_id,
      "species": "PM10",
      "value": pd.to_numeric(pulled_AGreadings["pm10"], errors = "coerce"),
      "status": "latest"
    }]
  dfAG_result = pd.DataFrame(rows)
  return dfAG_result

# Check if the above worked
dfAG_test = AG_pulled_readings_to_ss(AG_pulled_readings)
print(dfAG_test)

# Creating the snapshot dataframe that stores the required data
# Used for loop so that when adding new devices during registration it'll work
dfAG_ss = []

for _, row in dfAG_devices.iterrows():
  location_id = row["device_id"]

  try:
    df_one = AG_pulled_readings_to_ss(AG_pulled_readings)
    if not df_one.empty:
      dfAG_ss.append(df_one)
  except Exception as e:
    print(f"Error processing location ID {location_id}: {e}")

  if dfAG_ss:
    dfAG_ss = pd.concat(dfAG_ss, ignore_index = True)
  else:
    dfAG_ss = pd.DataFrame(columns = ["time", "device_id", "species", "value", "status"])

print(dfAG_ss)

"""#**Ensuring that the device ID was added into the Devices table before seeding the readings into the Readings table**

Because in the event it was not done, this step ensures no errors arise.
"""

# To match the devices seeded in Devices table
# Removing the unmatched Devices
df_devices_db = pd.read_sql("SELECT device_id FROM devices;", engine)
valid_devices_id = set(df_devices_db["device_id"].astype(str))

dfAG_ss = dfAG_ss[
    dfAG_ss["device_id"].astype(str).isin(valid_devices_id)
].copy()

print("Rows after applying filter. Output for valid ss readings devices:", len(dfAG_ss))

# Time to seed AirGradient readings into the Readings table
seed_readings(dfAG_ss, engine)

# Double check from Readings table
verify_df = pd.read_sql("""
SELECT * FROM readings WHERE device_id IN (
    SELECT device_id FROM devices WHERE source = 'airgradient'
)""", engine)
print(verify_df)

unified_sql_query = """
WITH latest_readings AS (
  SELECT
    r.device_id,
    r.species,
    r.value,
    r.time,
    ROW_NUMBER() OVER (
      PARTITION BY r.device_id, r.species
      ORDER BY r.time DESC
    ) AS rn
  FROM readings r
),
-- keeping only the latest reading because Render can't support historical data (too big)
latest_only AS(
    SELECT
      device_id,
      species,
      value,
      time
    FROM latest_readings
    -- because the readings are ranked from latest (desc order)
    -- 1 is calling the top reading for each device/species
    WHERE rn = 1
)
SELECT
  d.device_id,
  d.source,
  d.device_name,
  d.school_id,
  s.school_name,
  s.school_type,
  s.postcode,
  s.borough,
  s.centroid_lat AS latitude,
  s.centroid_lon AS longitude,
-- MAX ignores null values as CASE WHEN filters by species (value or null) per device
  MAX(CASE WHEN lo.species = 'PM25' THEN lo.value END) AS "PM2.5",
  MAX(CASE WHEN lo.species ='PM10' THEN lo.value END) AS "PM10",
  MAX(CASE WHEN lo.species = 'NO2' THEN lo.value END) AS "NO2",

  MAX(CASE WHEN lo.species = 'PM25' THEN lo.time END) AS "PM2.5_time",
  MAX(CASE WHEN lo.species ='PM10' THEN lo.time END) AS "PM10_time",
  MAX(CASE WHEN lo.species = 'NO2' THEN lo.time END) AS "NO2_time"

FROM devices d
JOIN schools s
  ON d.school_id = s.school_id
LEFT JOIN latest_only lo
  ON d.device_id = lo.device_id
-- use GROUP BY to get one row per device
GROUP BY
  d.device_id,
  d.source,
  d.device_name,
  d.school_id,
  s.school_name,
  s.school_type,
  s.postcode,
  s.borough,
  s.centroid_lat,
  s.centroid_lon

ORDER BY
  d.source,
  s.school_name,
  d.device_id;
"""
import plotly.express as px
import pandas as pd

df_unified = pd.read_sql(unified_sql_query, engine)
print(df_unified)

"""#Debugging code to fix the issue: Multiple device IDs are being assigned to the same school ID, thus the codes below is to find out which part of the above code is creating the issue."""

# This is to check where the issue is
pd.read_sql("""
SELECT school_id, COUNT(*) AS n
FROM devices
GROUP BY school_id
ORDER BY n DESC
LIMIT 20;
""", engine)

pd.read_sql("""
SELECT *
FROM schools
WHERE school_id = '100000';
""", engine)

"""#I have discovered that the issue is when I was mapping the inner postcode centroid London dataframe to the Breathe London dataframe.

Therefore, I am going to write a query that will delete Breathe Londons' data from the readings and devices tables in SQL Alchemy.
"""

with engine.begin() as connection:
  connection.execute(text("""
      DELETE from readings
      WHERE device_id IN(
        SELECT device_id
        FROM devices
        WHERE source = 'breathe_london'
      );
  """))
print("Breathe London readings deleted.")

with engine.begin() as connection:
  connection.execute(text("""
      DELETE from devices
      WHERE source = 'breathe_london';
  """))
print("Breathe London devices deleted.")

# Confirming this has been done by checking if these tables only have AirGradient data seeded
pd.read_sql("""
SELECT source, COUNT (*)
FROM devices
GROUP BY source;
""", engine)