# -*- coding: utf-8 -*-
"""SQL_Tables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6TxiUdY38XlkfqG6g_10etqR4_tMnb2
"""

!pip install sqlalchemy psycopg2-binary

import os
from sqlalchemy import create_engine, text

# Creating a connection point for my Breathe & Airgradient ingestion codes, dashboard queries, and schema setup
os.environ["DATABASE_URL"] = "postgresql://ywsjl2130:KqVwIi3iqlz15pVuvKGB6ynpBF4e6rEZ@dpg-d7edd6hkh4rs73aarmlg-a.oregon-postgres.render.com/timescaledb_473l"

def get_database_URL ():
  URL = os.environ.get("DATABASE_URL")
  if not URL:
    raise RuntimeError("Database URL is not set up")
  return URL

# Creating a connection manager for python code to interact with PostgreSQL
engine = create_engine(
    get_database_URL(),
    # Prevents stale connections as some connections may be "sleeping"
    pool_pre_ping = True,
    # This is so that SQL uses its latest style
    future = True
)

with engine.connect() as connection:
  result = connection.execute(text("SELECT NOW()")) # lets Alchemy know that it's a SQL query and not python
  print(result.scalar())

from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("CREATE EXTENSION timescaledb;"))

from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT extname
        FROM pg_extension
        WHERE extname = 'timescaledb';
    """))
    print(result.fetchall())

with engine.connect() as conn:
  result = conn.execute(text("""
      SELECT proname
      FROM pg_proc
      WHERE proname = 'create_hypertable';
  """))
  print(result.fetchall())

sql_file = """
CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS schools (
    school_id TEXT PRIMARY KEY,
    school_name TEXT NOT NULL,
    school_type TEXT,
    postcode TEXT NOT NULL,
    borough TEXT,
    centroid_lat DOUBLE PRECISION,
    centroid_lon DOUBLE PRECISION,
    install_date DATE
);

CREATE TABLE IF NOT EXISTS devices (
    device_id TEXT PRIMARY KEY,
    source TEXT NOT NULL, -- breatheLondon or AirGradient
    school_id TEXT REFERENCES schools(school_id),
    device_name TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS readings (
    time TIMESTAMPTZ NOT NULL,
    device_id TEXT NOT NULL REFERENCES devices(device_id),
    species TEXT NOT NULL, --pollutant type
    value DOUBLE PRECISION,
    status TEXT NOT NULL
);

SELECT create_hypertable('readings', 'time', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS idx_readings_device_time ON readings (device_id, time DESC);

CREATE INDEX IF NOT EXISTS idx_readings_species_time ON readings (species, time DESC);
"""

with engine.begin() as connection:
  for stmt in sql_file.split(";"):
    stmt = stmt.strip()
    if stmt:
      connection.execute(text(stmt))
print("Schema created successfully!")

# Checking if the tables and hypertable was created
from sqlalchemy import text

with engine.connect() as conn:
    print(conn.execute(text("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
        ORDER BY table_name;
    """)).fetchall())

with engine.connect() as conn:
    print(conn.execute(text("""
        SELECT hypertable_name
        FROM timescaledb_information.hypertables;
    """)).fetchall())