# -*- coding: utf-8 -*-
"""SQL_Creation_APIs_Ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7IWSD9d-TL2aFILAf8_yQzidYC603Xq

# **Creating the SQL tables**
"""

!pip install sqlalchemy psycopg2-binary

import os
from sqlalchemy import create_engine, text

# Creating a connection point for my Breathe & Airgradient ingestion codes, dashboard queries, and schema setup
#os.environ["DATABASE_URL"] = "postgresql://ywsjl2130:KqVwIi3iqlz15pVuvKGB6ynpBF4e6rEZ@dpg-d7edd6hkh4rs73aarmlg-a.oregon-postgres.render.com/timescaledb_473l"

def get_database_URL ():
  #URL = os.environ.get("DATABASE_URL")
  URL = os.getenv("DATABASE_URL")
  if not URL:
    raise RuntimeError("Database URL is not set up")
  return URL

# Creating a connection manager for python code to interact with PostgreSQL
engine = create_engine(
    get_database_URL(),
    # Prevents stale connections as some connections may be "sleeping"
    pool_pre_ping = True,
    # This is so that SQL uses its latest style
    future = True
)

with engine.connect() as connection:
  result = connection.execute(text("SELECT NOW()")) # lets Alchemy know that it's a SQL query and not python
  print(result.scalar())

with engine.begin() as conn:
    conn.execute(text("CREATE EXTENSION timescaledb;"))

with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT extname
        FROM pg_extension
        WHERE extname = 'timescaledb';
    """))
    print(result.fetchall())

with engine.connect() as conn:
  result = conn.execute(text("""
      SELECT proname
      FROM pg_proc
      WHERE proname = 'create_hypertable';
  """))
  print(result.fetchall())

sql_file = """
CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS schools (
    school_id TEXT PRIMARY KEY,
    school_name TEXT NOT NULL,
    school_type TEXT,
    postcode TEXT NOT NULL,
    borough TEXT,
    centroid_lat DOUBLE PRECISION,
    centroid_lon DOUBLE PRECISION,
    install_date DATE
);

CREATE TABLE IF NOT EXISTS devices (
    device_id TEXT PRIMARY KEY,
    source TEXT NOT NULL, -- breatheLondon or AirGradient
    school_id TEXT REFERENCES schools(school_id),
    device_name TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS readings (
    time TIMESTAMPTZ NOT NULL,
    device_id TEXT NOT NULL REFERENCES devices(device_id),
    species TEXT NOT NULL, --pollutant type
    value DOUBLE PRECISION,
    status TEXT NOT NULL
);

SELECT create_hypertable('readings', 'time', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS idx_readings_device_time ON readings (device_id, time DESC);

CREATE INDEX IF NOT EXISTS idx_readings_species_time ON readings (species, time DESC);
"""

with engine.begin() as connection:
  for stmt in sql_file.split(";"):
    stmt = stmt.strip()
    if stmt:
      connection.execute(text(stmt))
print("Schema created successfully!")

# Checking if the tables and hypertable was created
from sqlalchemy import text

with engine.connect() as conn:
    print(conn.execute(text("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
        ORDER BY table_name;
    """)).fetchall())

with engine.connect() as conn:
    print(conn.execute(text("""
        SELECT hypertable_name
        FROM timescaledb_information.hypertables;
    """)).fetchall())

"""# **Inserting data into the school table**"""

import pandas as pd

df_pcIL = pd.read_csv("https://raw.githubusercontent.com/ywsjl/Air-Pulse-Air-Quality-Map-Dashboard/refs/heads/main/postcode_centroid_inner_london_schools.csv")
list(df_pcIL.columns)

# Checking to see if the data types for the variables are correct
# Before I insert data into the school table
print(df_pcIL.dtypes)

# Dropping any duplicates because I forgot to do that previously
df_pcIL = df_pcIL.drop_duplicates(subset = ["school_id"])
# Need to rename longitude and latitude as its diff under the SQL table
df_pcIL = df_pcIL.rename(columns = {
    "centroid_latitude": "centroid_lat",
    "centroid_longitude":"centroid_lon"
})
list(df_pcIL.columns)

insert_sql = """
    INSERT INTO schools (
      school_id,
      school_name,
      school_type,
      postcode,
      borough,
      centroid_lat,
      centroid_lon
    )
    -- assigning data into the tables
    VALUES(
      :school_id,
      :school_name,
      :school_type,
      :postcode,
      :borough,
      :centroid_lat,
      :centroid_lon
    )
    -- This helps update the existing schools instead of crashing
    ON CONFLICT (school_id) DO UPDATE SET
      school_name = EXCLUDED.school_name,
      school_type = EXCLUDED.school_type,
      postcode = EXCLUDED.postcode,
      borough = EXCLUDED.borough,
      centroid_lat = EXCLUDED.centroid_lat,
      centroid_lon = EXCLUDED.centroid_lon
"""

with engine.begin() as connection:
  connection.execute(text(insert_sql), df_pcIL.to_dict(orient = "records"))

print("Schools database is successfully populated (seeded).")

# Double check it actually got seeded

verify_df = pd.read_sql("SELECT * FROM schools LIMIT 5", engine)
print(verify_df)

"""# **Breathe London API Ingestion**"""

import requests
import plotly.express as px
import re

# API consumption using BreatheLondon's API
API_key = os.getenv("BL_API_KEY")
# The metadata for list sensors will be used to place markers on the map
# Sensor data is to colour code the markers and show the readings
List_sensors_URL = "https://breathe-london-7x54d7qf.ew.gateway.dev/ListSensors"
Sensor_data_URL = "https://breathe-london-7x54d7qf.ew.gateway.dev/SensorData"
# Creating a dict of http headers to send a request to the Breathe London server to get what I need from the API
# Following the website (Breathe London) they said I need 2 headers to call the metadata
BL_headers = {
    "X-API-KEY": BL_API_KEY,
    "Content-Type": "application/json"
}

# Now I can request for json metadata
# I can check if the requests is working through the 2nd line
def get_metadata():
  r = requests.get(List_sensors_URL, headers = BL_headers, timeout = 60)
  r.raise_for_status()
# Since the json file isn't in the correct format for python, I have to convert it into the proper dict that python understands
  return pd.DataFrame(r.json())

# Small EDA to see if the above is running smoothly, the features in the metadata, and number of sensors they have
df_sensors = get_metadata()
# Filtering the dataframe so that location = school only appears
df_sensors = df_sensors[
    df_sensors["SiteLocationType"].astype(str).str.lower() == "school"
].copy()
# Checking if the above code worked and only give school devices
print(df_sensors["SiteLocationType"].unique())
print(len(df_sensors))
print(df_sensors.columns.tolist())

# Normalising the school names
def normalise_sch_name(name):
  if pd.isna(name):
    return None
  name = str(name).lower().strip()
  name = name.replace("&","and")
  # Removing punctuation
  name = re.sub(r"[^\w\s]", " ", name)
  # Removing multiple spaces and replacing with a single space
  name = re.sub(r"[^\s+]"," ", name)
  # To remove abbreviations
  replacements = {
      "cofe": " ",
      "c of e": " ",
      "rc": " ",
      "roman catholic": " "
  }
  # This is to prvent accidentally getting rid of alphabets in the school name
  # By adding a space in front and behind
  padded = f"{name}"
  for old, new in replacements.items():
    padded = padded.replace(old,new)
  return re.sub(r"\s+", " ", padded).strip()

def normalise_borough(y):
  if pd.isna(y):
    return None
  return str(y).strip().lower()
# Creating a new column in each dataframe for the normalised schools
df_sensors["school_name_norm"] = df_sensors["SiteName"].apply(normalise_sch_name)
df_sensors["borough_norm"] = df_sensors["Borough"].apply(normalise_borough)
df_pcIL["school_name_norm"] = df_pcIL["school_name"].apply(normalise_sch_name)
df_pcIL["borough_norm"] = df_pcIL["borough"].apply(normalise_borough)

"""# **Merging Breathe London sensors to postcode centroid inner London schools to create a new dataframe**"""

df_match_both = (
    df_pcIL.sort_values("school_id")
    .drop_duplicates(subset = ["school_name_norm", "borough_norm"]).copy()
)
df_schools_name_match = (
    df_pcIL.sort_values("school_id")
    .drop_duplicates(subset = ["school_name_norm"]).copy()
)

df_match_both = df_sensors.merge(
    df_match_both[
        [
            "school_id",
            "school_name",
            "school_name_norm",
            "school_type",
            "postcode",
            "borough",
            "borough_norm",
            "centroid_lat",
            "centroid_lon"
        ]
    ],
    on = ["school_name_norm","borough_norm"],
    how = "left",
    suffixes = ("_sensor", "_school")
)

df_unmatched = df_match_both[df_match_both["school_id"].isna()].copy()
print("Unmatched schools:", len(df_unmatched))

df_schools_name_match = df_unmatched.drop(
    columns = [
        "school_id",
        "school_name",
        "postcode",
        "centroid_lat",
        "centroid_lon"], errors = "ignore"
).merge(
    df_schools_name_match[
        ["school_id",
        "school_name",
        "school_name_norm",
        "school_type",
        "postcode",
        "centroid_lat",
        "centroid_lon"]
    ],
    on = "school_name_norm",
    how = "left"
)

df_first_match = df_match_both[df_match_both["school_id"].notna()].copy()
df_second_match = df_schools_name_match[df_schools_name_match["school_id"].notna()].copy()

df_sensors_school = pd.concat([df_first_match, df_second_match], ignore_index = True)
df_sensors_school = df_sensors_school.drop_duplicates(subset = ["SiteCode"], keep = "first")
print("Matched sensors:", df_sensors_school["school_id"].notna().sum())
print("Total sensors:",len(df_sensors_school))

# Changing all the coordinates from Breathe London to centroid coordinates
df_sensors_school["Latitude"] = df_sensors_school["centroid_lat"]
df_sensors_school["Longitude"] = df_sensors_school["centroid_lon"]

df_devices = df_sensors_school[df_sensors_school["school_id"].notna()].copy
df_devices = df_sensors_school[
    ["SiteCode",
     "SiteName",
     "school_id"
    ]
].copy()

df_devices = df_devices.rename(
    columns = {
        "SiteCode": "device_id",
        "SiteName": "device_name"
    }
)

df_devices["source"] = "breathe_london"
df_devices = df_devices[["device_id","source","school_id","device_name"]]

print(df_devices.head())

"""# **Inserting data into the device table**"""

print(df_devices.dtypes)

def seed_devices(df_devices, engine):
  required_cols = ["device_id", "source", "school_id","device_name"]
  missing = [col for col in required_cols if col not in df_devices.columns]
  if missing:
    raise ValueError(f"Missing required columns:{missing}")

  df_devices = df_devices[required_cols].copy()
  # To keep it consistent with schools table
  df_devices["school_id"] = pd.to_numeric(
      df_devices["school_id"],
      errors = "coerce"
  ).astype("Int64").astype(str)

  db_school_id = pd.read_sql(
      "SELECT school_id FROM schools",
      engine
  )
  valid_school_ids = set(db_school_id["school_id"].astype(str).tolist())

  df_devices = df_devices[df_devices["school_id"].isin(valid_school_ids)].copy()
  print("Rows ready to be inserted:", len(df_devices))

  insert_devices_sql = """
    INSERT INTO devices(
      device_id,
      source,
      school_id,
      device_name
    )
    VALUES(
      :device_id,
      :source,
      :school_id,
      :device_name
    )
    ON CONFLICT (device_id) DO UPDATE SET
      source = EXCLUDED.source,
      school_id = EXCLUDED.school_id,
      device_name = EXCLUDED.device_name
  """
  records = df_devices.to_dict(orient = "records")
  with engine.begin() as connection:
    connection.execute(text(insert_devices_sql), records)
  print("Devices database is successfully populated (seeded).")

seed_devices(df_devices, engine)

# Double check it actually got seeded

verify_df = pd.read_sql("SELECT * FROM devices LIMIT 5", engine)
print(verify_df)

"""# **Calling the necessary data needed for the Breathe London Readings dataframe.**"""

# Using the sensor data url to call the necessary latest readings which is PM2.5 & NO2
def sensor_readings(species):
  parameters = {"Species": species}
  readings_data = requests.get(Sensor_data_URL, headers = BL_headers, timeout = 60, params= parameters)
  readings_data.raise_for_status()
# Since the json file isn't in the correct format for python, I have to convert it into the proper dict that python understands
  return pd.DataFrame(readings_data.json())

# Small EDA to see if the above is running smoothly, the features in the metadata, and number of sensors they have
dfBL_PM25 = sensor_readings("PM25")
dfBL_NO2 = sensor_readings("NO2")
print("PM2.5 Readings", len(dfBL_PM25))
print("NO2 Readings", len(dfBL_NO2))

def latest_snapshot(dfBL, species_name):
  # Keeping only the features required
  dfBL = dfBL[["SiteCode","ScaledValue","DateTime","Species"]].copy()

  # This converts the str DateTime pulled from the API to an actual datetime format
  # In case some of the string cant be converted I used errors so that it will not crash the code
  dfBL["DateTime"] = pd.to_datetime(dfBL["DateTime"], errors = "coerce", utc = True)
  dfBL["ScaledValue"] = pd.to_numeric(dfBL["ScaledValue"], errors = "coerce")

  # Keep the latest readings per sensor per site code (school)
  # Tail (1) gives me the last row from each group which is the latest reading
  dfBL = dfBL.sort_values("DateTime").groupby("SiteCode").tail(1)

  # To match the Readings table
  dfBL = dfBL.rename(columns = {
        "SiteCode": "device_id",
        "DateTime": "time",
        "ScaledValue": "value",
        "Species": "species"
  })
  dfBL["status"] = "latest"

  # Getting rid of invalid rows
  dfBL = dfBL.dropna(subset = ["time", "device_id", "value","species"]).copy()

  return dfBL

# Creating the pollutants snapshot dataframes and merging them
dfBL_ss_PM25 = latest_snapshot(dfBL_PM25, "PM25")
dfBL_ss_NO2 = latest_snapshot(dfBL_NO2, "NO2")

dfBL_ss = pd.concat(
    [dfBL_ss_PM25, dfBL_ss_NO2],
    ignore_index = True
)

# Checking if it worked
# It should roughly correspond with total number of readings,242. (from EDA output)
print(dfBL_ss.head())
print("Rows in Breathe London snapshot:", len(dfBL_ss))

"""#**Ensuring that the device ID was added into the Devices table before seeding the readings into the Readings table**

Because in the event it was not done, this step ensures no errors arise.
"""

# To match the devices seeded in Devices table
# Removing the unmatched Devices
df_devices_db = pd.read_sql("SELECT device_id FROM devices;", engine)
valid_devices_id = set(df_devices_db["device_id"].astype(str))

dfBL_ss = dfBL_ss[
    dfBL_ss["device_id"].astype(str).isin(valid_devices_id)
].copy()

print("Rows after applying filter. Output for valid ss readings devices:", len(dfBL_ss))

"""The output for valid ss reading devices are 87 because 14 of the devices that were seeded in the Devices table do not have a reading currently.

# **Inserting these readings into the Readings table.**
"""

# Editing the Readings table because I need to add constraints
# To use in ON CONFLICT which prevents adding duplicate readings
with engine.begin() as connection:
  connection.execute(text("""
      ALTER TABLE readings
      ADD CONSTRAINT unique_reading
      -- all 3 is required because even though id is unique
      -- since there are multiple pollutants, there will be more than 1 of the same id
      UNIQUE (time,device_id,species)
  """))

print("Unique constraints have been added to Readings table.")

def seed_readings(df_readings, engine):
  required_cols = ["time", "device_id", "species","value", "status"]
  missing = [col for col in required_cols if col not in df_readings.columns]
  if missing:
    raise ValueError(f"Missing required columns:{missing}")

  df_readings = df_readings[required_cols].copy()
  # For Nan values
  df_readings = df_readings.dropna(subset = ["time", "device_id", "species","value"]).copy()
  # In case of duplicates
  df_readings = df_readings.drop_duplicates(subset = ["time", "device_id", "species"])

  print("Rows ready to be inserted:", len(df_readings))
  print(df_readings.head())

  insert_readings_sql = """
    INSERT INTO readings(
      time,
      device_id,
      species,
      value,
      status
    )
    VALUES(
      :time,
      :device_id,
      :species,
      :value,
      :status
    )
    ON CONFLICT (time, device_id, species) DO UPDATE SET
      value = EXCLUDED.value,
      status = EXCLUDED.status
  """

  records = df_readings.to_dict(orient = "records")
  with engine.begin() as connection:
    connection.execute(text(insert_readings_sql), records)
  print("Readings database is successfully populated (seeded).")

seed_readings(dfBL_ss, engine)

# Double check it actually got seeded
verify_df = pd.read_sql("SELECT * FROM readings LIMIT 5", engine)
print(verify_df)

"""# **Creating Air Gradient manual registry**

AirGradient's API URLs require location ID which is unique to each device as it is a private data platform. However, as I do not have all the location ID for inner London I cannot pull the metadata.

Thus, I have decided create a small manual registry and will connect this to the device registration.

The school ID that will be used below is not from a device placed in a school. But for this coursework, I applied an approximate mapping for the device which resulted in Millbank Gardens Primary Academy, being selected as it's the closest coordinates to the device.
"""

dfAG_registry = pd.DataFrame([
  {
      "device_id": "151755",
      "device_name": "Westminster, Horseferry Road",
      "school_id": "151310"
  }
])

dfAG_registry["source"] = "airgradient"
print(dfAG_registry)

"""#**Seeding Air Gradient device to Devices table**"""

dfAG_devices = dfAG_registry[
    ["device_id", "source", "school_id", "device_name"]
].copy()

# Assigning the data type
dfAG_devices["device_id"] = dfAG_devices["device_id"].astype(str)
dfAG_devices["source"] = dfAG_devices["source"].astype(str).str.strip().str.lower()
dfAG_devices["school_id"] = pd.to_numeric(dfAG_devices["school_id"], errors = "coerce").astype("Int64")
dfAG_devices["device_name"] = dfAG_devices["device_name"].astype(str).str.strip()

print(dfAG_devices.dtypes)
print(dfAG_devices)

seed_devices(dfAG_devices, engine)

# Double checking if it was seeded
print(pd.read_sql("SELECT * FROM devices WHERE source = 'airgradient'", engine))

"""# **Air Gradient API Ingestion**

"""

# API consumption using AirGradient's API
API_key = os.getenv("AG_API_KEY")

def AGcurrent_measures(location_id):
  # Using this API to get the current reading of the device
  locations_URL = f"https://api.airgradient.com/public/api/v1/locations/{location_id}/measures/current?token={AG_API_KEY}"

  # Now I can request for json metadata
  # I can check if the requests is working through the 2nd line
  r = requests.get(locations_URL, headers = headers, timeout = 60)
  r.raise_for_status()
  return r.json()

# Checking if it works
AG_pulled_readings = AGcurrent_measures("151755")
print(AG_pulled_readings)

"""#**Renaming the columns to match Readings table**"""

def AG_pulled_readings_to_ss(pulled_AGreadings):
  timestamp = pulled_AGreadings.get("timestamp")
  timestamp = pd.to_datetime(timestamp, errors = "coerce", utc= True)

  device_id = str(pulled_AGreadings.get("locationId"))

  rows = [
      {
      "time": timestamp,
      "device_id": device_id,
      "species": "PM25",
      "value": pd.to_numeric(pulled_AGreadings["pm02"], errors = "coerce"),
      "status": "latest"
  },
    {
      "time": timestamp,
      "device_id": device_id,
      "species": "PM10",
      "value": pd.to_numeric(pulled_AGreadings["pm10"], errors = "coerce"),
      "status": "latest"
    }]
  dfAG_result = pd.DataFrame(rows)
  return dfAG_result

# Check if the above worked
dfAG_test = AG_pulled_readings_to_ss(AG_pulled_readings)
print(dfAG_test)

# Creating the snapshot dataframe that stores the required data
# Used for loop so that when adding new devices during registration it'll work
dfAG_ss = []

for _, row in dfAG_devices.iterrows():
  location_id = row["device_id"]

  try:
    df_one = AG_pulled_readings_to_ss(AG_pulled_readings)
    if not df_one.empty:
      dfAG_ss.append(df_one)
  except Exception as e:
    print(f"Error processing location ID {location_id}: {e}")

  if dfAG_ss:
    dfAG_ss = pd.concat(dfAG_ss, ignore_index = True)
  else:
    dfAG_ss = pd.DataFrame(columns = ["time", "device_id", "species", "value", "status"])

print(dfAG_ss)

"""#**Ensuring that the device ID was added into the Devices table before seeding the readings into the Readings table**

Because in the event it was not done, this step ensures no errors arise.
"""

# To match the devices seeded in Devices table
# Removing the unmatched Devices
df_devices_db = pd.read_sql("SELECT device_id FROM devices;", engine)
valid_devices_id = set(df_devices_db["device_id"].astype(str))

dfAG_ss = dfAG_ss[
    dfAG_ss["device_id"].astype(str).isin(valid_devices_id)
].copy()

print("Rows after applying filter. Output for valid ss readings devices:", len(dfAG_ss))

# Time to seed AirGradient readings into the Readings table
seed_readings(dfAG_ss, engine)

# Double check from Readings table
verify_df = pd.read_sql("""
SELECT * FROM readings WHERE device_id IN (
    SELECT device_id FROM devices WHERE source = 'airgradient'
)""", engine)
print(verify_df)